# Generated by Django 2.1.7 on 2019-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='company',
            field=models.CharField(default='Unknown', max_length=250),
        ),
    ]
